# Generated by Django 3.0.4 on 2020-03-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=30)),
                ('open', models.DecimalField(decimal_places=2, max_digits=30)),
                ('high', models.DecimalField(decimal_places=2, max_digits=30)),
                ('low', models.DecimalField(decimal_places=2, max_digits=30)),
                ('close', models.DecimalField(decimal_places=2, max_digits=30)),
                ('last', models.DecimalField(decimal_places=2, max_digits=30)),
                ('prevclose', models.DecimalField(decimal_places=2, max_digits=30)),
                ('tottrdqty', models.IntegerField()),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
