# Generated by Django 3.0.4 on 2020-03-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equities',
            old_name='close',
            new_name='CLOSE',
        ),
        migrations.RenameField(
            model_name='equities',
            old_name='high',
            new_name='HIGH',
        ),
        migrations.RenameField(
            model_name='equities',
            old_name='last',
            new_name='LAST',
        ),
        migrations.RenameField(
            model_name='equities',
            old_name='low',
            new_name='LOW',
        ),
        migrations.RenameField(
            model_name='equities',
            old_name='open',
            new_name='OPEN',
        ),
        migrations.RenameField(
            model_name='equities',
            old_name='prevclose',
            new_name='PREVCLOSE',
        ),
        migrations.RenameField(
            model_name='equities',
            old_name='series',
            new_name='SERIES',
        ),
        migrations.RenameField(
            model_name='equities',
            old_name='symbol',
            new_name='SYMBOL',
        ),
        migrations.RenameField(
            model_name='equities',
            old_name='timestamp',
            new_name='TIMESTAMP',
        ),
        migrations.RenameField(
            model_name='equities',
            old_name='tottrdqty',
            new_name='TOTTRDQTY',
        ),
    ]
